#define MAX_DATA_BLOCK 4096

#define WRONG_ARGUMENT_ERROR_CODE -1
#define WRONG_NUMBER_OF_LAUNCHED_PROCESSES -2
#define NOT_ENOUGHT_DATA_FOR_PROCESSES -3
#define WRONG_FILE_PATH -4
#define STATUS_OK 0

#define ROOT 0
